// Handover prose shared by /fm/handover (legacy page) and the v2 Admin ›
// Handover view. Static content — no secrets; the .env is referenced by name only.
// Block shapes: { p } · { code } · { note: { tone, text } } · { table: { head, rows } } · { ul: [] }
// Inline markup inside text: **bold** and `code`.

// Plain-English explanation of what each table holds, for a non-technical reader.
export const TABLE_DOCS = {
  // ── core / transition data ──
  factions: "The master list of every faction: name, tier, leader, links, and whether it has been archived. The single most important table.",
  faction_history: "A dated timeline of everything that happened to each faction — promotions, edits, and staff notes.",
  faction_members: "The member roster for each faction.",
  faction_reviews: "Monthly leadership reviews and recommendations for each faction.",
  faction_public_messages: "Public notices and announcements shown on each faction's page.",
  faction_ic_contacts: "In-character contact requests sent to factions (story requests).",
  faction_ic_messages: "The back-and-forth messages on those in-character contacts.",
  faction_imports: "Which import items each faction has been permitted to have.",
  faction_fleet_config: "Settings for the faction vehicle (fleet) feature.",
  faction_fleet_garages: "Each faction's garages, where their vehicles are kept.",
  faction_fleet_vehicles: "The actual vehicles owned by each faction.",
  properties: "Every property and location tied to factions — HQs, safehouses, and so on.",
  npcs: "Every non-player character in the world, with their area (turf) and type.",
  spawn_items: "The catalog of in-game items (weapons, etc.) that can be spawned for scenes and NPCs.",
  import_items: "The master catalog of items factions can import, with tier and price.",
  inventory_stock: "The list of items that can be given out in a scene. The stock-count columns are historic and no longer maintained.",
  inventory_logs: "Every item handed out in a scene — what, how many, by whom.",
  fleet_vehicle_catalog: "The reference list of all vehicle types in the game.",
  weapon_ammo: "Reference list of ammunition types.",
  weapon_ammo_compat: "Which ammunition works with which weapons.",
  weapon_attachments: "Reference list of weapon attachments.",
  treasury_logs: "Money going in and out of faction treasuries.",
  pipedown_items: "The menu of items for the in-character shop (“Pipe Down”).",
  pipedown_orders: "Customer orders placed through the Pipe Down shop.",
  pipedown_order_items: "The individual items within each Pipe Down order.",
  scene_logs: "A record of every roleplay scene that was run, with its date and faction.",
  scene_assistants: "Which staff members assisted on each scene.",
  scene_library: "Saved, reusable scene ideas and templates.",
  scene_library_feedback: "Feedback left on scene-library entries.",
  ooc_notes: "Out-of-character notes attached to scenes.",
  change_log: "A log of world and story changes — drop locations, turf edits, and similar.",
  promotion_polls: "Polls used when deciding faction promotions.",
  knowledge_base: "The team's how-to articles and reference information.",
  intel_notes: "Intelligence notes staff recorded about factions and players.",
  documents: "Uploaded documents and guides stored for the team.",
  staff: "The FM staff roster — names, ranks, teams, and access level.",
  staff_coi: "Staff conflicts of interest — factions a staffer is not allowed to oversee.",
  teams: "The FM teams and the Discord channel each one uses.",
  fm_character_links: "Links between staff members and their in-game characters.",
  fm_hours_log: "A log of staff activity hours.",
  leadership_meeting_notes: "Notes from leadership meetings.",
  leadership_personal_notes: "Private notes kept by individual leaders.",
  discord_config: "Which Discord channels the bot posts to (announcements, pings, etc.).",
  discord_roles: "The Discord roles the system recognizes (leadership, guides, etc.).",
  bot_server_configs: "Per-Discord-server settings for the bot.",
  dashboard_access: "People granted special access to this website.",
  mdb_access_roles: "Which Discord roles may enter the member-facing database site.",
  // ── transient / logs (excluded from the bundle) ──
  discord_messages: "A raw archive of Discord messages the bot logged. Very large, and not needed to run FM.",
  edited_message_logs: "A record of edited Discord messages (moderation history).",
  deleted_message_logs: "A record of deleted Discord messages (moderation history).",
  mentions: "A log of pings the bot noticed.",
  role_mentions: "A log of role pings.",
  watch_role_mentions: "A log of pings for specially-watched roles.",
  member_join_leave_logs: "A log of people joining and leaving the Discord server.",
  site_audit_log: "A record of actions taken on this website.",
  tasks: "To-do tasks that are currently open (temporary).",
  task_log: "History of completed and edited tasks.",
  task_questions: "Questions people asked about tasks.",
  reminders: "One-off scheduled reminders.",
  recurring_reminders: "Repeating reminder setups.",
  recurring_reminder_instances: "Each scheduled firing of a repeating reminder.",
  sent_recurring_reminders: "A record of repeating reminders already sent.",
  reminder_purge_channels: "Channels where reminders get automatically cleared.",
  channel_sync_state: "Internal bookkeeping for the bot's channel syncing.",
  channel_purge_schedules: "Schedules for automatically clearing channels.",
  auto_delete_channels: "Channels set to auto-delete their messages.",
  conversation_summaries: "AI-generated summaries of conversations.",
  forwarded_dms: "Direct messages forwarded to staff.",
  keyword_alerts: "Records of watched keywords being triggered.",
  server_log_keywords: "The keywords the bot watches for.",
  bot_watch_roles: "Roles the bot keeps an eye on.",
  sessions: "Active website logins (temporary; the secret token is hidden).",
  mdb_sessions: "Active member-site logins (temporary; the secret token is hidden).",
  pending_executions: "Background jobs waiting to run.",
  deletion_requests: "Requests to delete something, awaiting action.",
  managed_forum_posts: "Forum posts the bot keeps updated.",
};

// ── the runbook content ──────────────────────────────────────────────────────
export const RUNBOOK = [
  {
    id: "start-here",
    title: "Start here",
    blocks: [
      { p: "**You do not need to be technical to use this page.** It has two jobs: keep every bit of the faction data safe forever, and give a tech-savvy helper the exact steps to put the system back online if you want to keep it running." },
      { note: { tone: "info", text: "**What Meridian is, in plain words:** three pieces working together — a **Discord bot** (the helper that lives in your Discord server), a **website** (the dashboard staff log into), and a **database** (one single file that holds *all* the data: factions, properties, NPCs, everything). The bot and the website are just windows into that one file." } },
      { p: "**Pick your path:**" },
      { ul: [
        "**Just want to keep the records safe?** Use the **database export** (the *Export the data* tab, or section 12 on the legacy page), download the database and the Sheets bundle, and save the files somewhere safe (Google Drive, a hard drive). That preserves everything — no server or website needed. You're done.",
        "**Want the website and bot to keep running?** Sections 1–11 are the setup steps. You are **not** expected to do these yourself — hand this page (or a printout) to a developer or a tech-savvy helper. Every step is written so a technical person can follow it exactly.",
      ] },
      { p: "**The four things you must protect — these are the keys to everything.** Make sure whoever takes over is given access to all four:" },
      { ul: [
        "**The secret settings file** (`.env`) — the system's passwords and keys.",
        "**The database file** (`meridian.db`) — every record. Keep backups of it.",
        "**The Cloudflare account** — controls the web address (ecrpfm.com).",
        "**The Discord developer account** — controls the bot itself.",
      ] },
      { note: { tone: "warn", text: "Losing any of those four is the only truly hard-to-undo part of a handover — transfer them deliberately, in writing." } },
      { note: { tone: "info", text: "**A few words you'll see, in plain English:** a **server** is a computer that runs 24/7 in the cloud · a **database** / **SQLite** is the single file holding the data · a **service** keeps a program running automatically · to **build** is to package the website so it can run · a **tunnel** connects the web address to the software · the **terminal** is the text window where a technical person types the commands shown in the grey boxes." } },
    ],
  },
  {
    id: "overview",
    title: "0 · What this stack is",
    blocks: [
      { p: "Meridian is two Node apps plus a shared SQLite database, all living under **`/opt/meridian`** on a single Linux (Debian/Ubuntu, systemd) host. The public site is fronted by a **Cloudflare Tunnel** — there is no local TLS/nginx for it." },
      { table: { head: ["Component", "Path", "How it runs"], rows: [
        ["Discord bot", "`/opt/meridian/bot` (discord.js 14, ESM)", "systemd `meridian-bot.service` → `node index.js`"],
        ["Dashboard", "`/opt/meridian/dashboard` (Next.js 15, app router)", "systemd `meridian-dashboard.service` → `start.sh` → `next start -p 3000`"],
        ["Shared DB layer", "`/opt/meridian/shared/db.js` (better-sqlite3, WAL)", "imported by both apps"],
        ["Database", "`/opt/meridian/data/meridian.db`", "SQLite WAL; path set by `DATABASE_PATH`"],
        ["Public proxy", "`cloudflared` tunnel", "`ecrpfm.com` → `localhost:3000` (supervised by PM2)"],
      ] } },
      { note: { tone: "info", text: "Both services read env from **`/opt/meridian/.env`** (`EnvironmentFile=` in each unit). The bot and dashboard share one DB file, so they must always point at the same `DATABASE_PATH`." } },
    ],
  },
  {
    id: "prereqs",
    title: "1 · Prepare the new server",
    blocks: [
      { note: { tone: "info", text: "**In plain terms:** this sets up a blank cloud computer with the basic tools the software needs. A technical helper does this once, near the start." } },
      { p: "Provision a Linux VM (Debian 12 / Ubuntu 22.04+ recommended). The current box runs on **~2 GB RAM** — that's the practical floor (Next builds are memory-hungry; see the build note in step 5)." },
      { p: "Install **Node 22.x** (current prod is `v22.22.2`), plus the build toolchain `better-sqlite3` needs to compile its native binding:" },
      { code: "# Node 22 (NodeSource)\ncurl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -\nsudo apt-get install -y nodejs\n\n# Build tools for better-sqlite3 native module + sqlite3 CLI + git\nsudo apt-get install -y build-essential python3 sqlite3 git rsync\n\nnode -v   # expect v22.x\nnpm -v    # expect 10.x" },
      { note: { tone: "warn", text: "Do **not** copy `node_modules/` from the old server. `better-sqlite3` is a compiled native module tied to the host's Node/ABI — reinstall it on the new box (step 4)." } },
    ],
  },
  {
    id: "backup",
    title: "2 · Snapshot the database (on the OLD server)",
    blocks: [
      { note: { tone: "info", text: "**In plain terms:** this makes one clean, complete copy of the single file that holds *all* the data. That copy is the most precious thing in this whole process — keep it safe." } },
      { p: "SQLite runs in **WAL mode**, so there are live `meridian.db-wal` / `-shm` sidecar files. Never copy the bare `.db` while the services are writing — use the `.backup` command, which produces a single consistent file with the WAL already folded in:" },
      { code: "cd /opt/meridian/data\nsqlite3 meridian.db \".backup '/tmp/meridian-migrate.db'\"\n\n# sanity check the snapshot\nsqlite3 /tmp/meridian-migrate.db \"PRAGMA integrity_check; SELECT COUNT(*) FROM staff; SELECT COUNT(*) FROM factions;\"" },
      { p: "`integrity_check` must print `ok`. This snapshot is your source of truth for the data — keep a copy somewhere safe before you touch anything else." },
      { note: { tone: "info", text: "The dashboard's **DB Site Access** and **Staff** pages, all faction/scene data, tasks, reminders, sessions, and audit logs all live in this one file. There is no external datastore to migrate." } },
    ],
  },
  {
    id: "code",
    title: "3 · Copy the code (on the OLD server)",
    blocks: [
      { p: "Bundle the application code and config, **excluding** regenerable/host-specific dirs (`node_modules`, `.next` build output, the live data dir, and local backups):" },
      { code: "cd /opt\ntar czf /tmp/meridian-code.tar.gz \\\n  --exclude='meridian/**/node_modules' \\\n  --exclude='meridian/dashboard/.next' \\\n  --exclude='meridian/data/*.db*' \\\n  --exclude='meridian/data/*.bak-*' \\\n  meridian" },
      { p: "Transfer both artifacts to the new server (adjust host/user), then unpack into `/opt`:" },
      { code: "# from the old server\nrsync -avz /tmp/meridian-code.tar.gz /tmp/meridian-migrate.db  NEWUSER@NEWHOST:/tmp/\n\n# on the NEW server\nsudo mkdir -p /opt\nsudo tar xzf /tmp/meridian-code.tar.gz -C /opt\nsudo mkdir -p /opt/meridian/data\nsudo cp /tmp/meridian-migrate.db /opt/meridian/data/meridian.db" },
      { note: { tone: "info", text: "The `.env` is intentionally left out of the code tarball (secrets). It's handled separately in step 4 — either copy it over a secure channel or rebuild it from the variable list." } },
    ],
  },
  {
    id: "env",
    title: "4 · Recreate the environment file & install deps",
    blocks: [
      { note: { tone: "info", text: "**In plain terms:** the `.env` file is the system's private passwords — never post it anywhere public. “Installing dependencies” just downloads the building blocks the code needs in order to run." } },
      { p: "Create **`/opt/meridian/.env`**. The fastest path is to `scp` the existing file from the old server (it contains the live secret values). If you'd rather rotate everything, rebuild it from this table — every variable both apps read:" },
      { table: { head: ["Variable", "Purpose / where to get it"], rows: [
        ["`DISCORD_CLIENT_ID`", "Discord app → General Information → Application ID"],
        ["`DISCORD_CLIENT_SECRET`", "Discord app → OAuth2 → Client Secret (can be reset)"],
        ["`DISCORD_BOT_TOKEN`", "Discord app → Bot → Token (Reset Token issues a new one)"],
        ["`GUILD_ID`", "The management Discord server ID (default `1457188814916423855`)"],
        ["`DATABASE_PATH`", "`/opt/meridian/data/meridian.db` — keep as-is"],
        ["`BASE_URL`", "`https://ecrpfm.com` — the public origin used to build OAuth redirects"],
        ["`NODE_ENV`", "`production`"],
        ["`SESSION_SECRET`", "Signs dashboard sessions. **Regenerate** with `openssl rand -hex 32` (logs everyone out — fine)"],
        ["`OPENAI_API_KEY`", "AI faction summaries (`/summarize`, summaries). Optional; features degrade without it"],
        ["`IMGBB_API_KEY`", "Image uploads (imgbb). Optional"],
        ["`NOTIFY_SECRET`", "Shared secret for the form-submission notify endpoint"],
        ["`AGENDA_SECRET`", "Shared secret for the read-only my-agenda endpoint"],
      ] } },
      { note: { tone: "danger", text: "Never commit `.env` or paste its **values** anywhere shared (including this page — that's why only names are listed). Lock it down: `chmod 600 /opt/meridian/.env`." } },
      { p: "Install dependencies for both apps (this compiles `better-sqlite3` for the new host):" },
      { code: "cd /opt/meridian/bot && npm ci\ncd /opt/meridian/dashboard && npm ci" },
      { note: { tone: "info", text: "If `npm ci` fails on the native build, confirm `build-essential` + `python3` are installed (step 1), then retry." } },
    ],
  },
  {
    id: "build",
    title: "5 · Build the dashboard",
    blocks: [
      { p: "The dashboard serves a **prebuilt** `.next`. `start.sh` deliberately refuses to build on boot (parallel builds OOM a small VM), so you must build once by hand before starting:" },
      { code: "cd /opt/meridian/dashboard\nnpm run build   # produces .next/BUILD_ID" },
      { note: { tone: "warn", text: "On a ~2 GB VM the build can be tight. If it gets OOM-killed, give Node more headroom: `NODE_OPTIONS=--max-old-space-size=1536 npm run build`, or add swap. The bot needs no build step." } },
    ],
  },
  {
    id: "services",
    title: "6 · Install the systemd services",
    blocks: [
      { note: { tone: "info", text: "**In plain terms:** this tells the computer to keep the bot and the website running on their own — and to restart them automatically after any reboot or crash." } },
      { p: "Recreate the two unit files exactly as they are in prod." },
      { p: "**`/etc/systemd/system/meridian-bot.service`**" },
      { code: "[Unit]\nDescription=Meridian Discord Bot\nAfter=network.target\nStartLimitIntervalSec=300\nStartLimitBurst=10\n\n[Service]\nEnvironmentFile=/opt/meridian/.env\nType=simple\nWorkingDirectory=/opt/meridian/bot\nExecStart=/usr/bin/node index.js\nRestart=always\nRestartSec=5\nEnvironment=NODE_ENV=production\n\n[Install]\nWantedBy=multi-user.target" },
      { p: "**`/etc/systemd/system/meridian-dashboard.service`**" },
      { code: "[Unit]\nDescription=Meridian Dashboard\nAfter=network.target\nStartLimitIntervalSec=0\n\n[Service]\nEnvironmentFile=/opt/meridian/.env\nType=simple\nWorkingDirectory=/opt/meridian/dashboard\nExecStart=/bin/bash /opt/meridian/dashboard/start.sh\nRestart=always\nRestartSec=10\nEnvironment=NODE_ENV=production\nEnvironment=NEXT_TELEMETRY_DISABLED=1\n\n[Install]\nWantedBy=multi-user.target" },
      { code: "sudo systemctl daemon-reload\nsudo systemctl enable --now meridian-bot meridian-dashboard\nsudo systemctl status meridian-bot meridian-dashboard --no-pager" },
      { note: { tone: "info", text: "`ExecStart` for the bot is `/usr/bin/node` — confirm `which node` matches, or adjust the path. If you run the services as a non-root user, make sure that user owns `/opt/meridian` and can write `data/`." } },
    ],
  },
  {
    id: "tunnel",
    title: "7 · Domain & TLS — Cloudflare Tunnel",
    blocks: [
      { note: { tone: "info", text: "**In plain terms:** this connects your public web address to the software, and Cloudflare provides the secure padlock (HTTPS) automatically — there are no certificates to buy or renew." } },
      { p: "`ecrpfm.com` is not served by nginx/Caddy — a **Cloudflare Tunnel** (`cloudflared`) forwards it to `localhost:3000`. TLS is terminated at Cloudflare's edge, so the new server needs no certificates. You can either move the existing tunnel or create a fresh one." },
      { p: "**Option A — reuse the existing tunnel** (least DNS churn): copy the tunnel credentials + config from the old box:" },
      { code: "# these came from the old server's /root/.cloudflared\n#   config.yml, cert.pem, <tunnel-id>.json\nsudo apt-get install -y cloudflared    # or per Cloudflare's install docs\nsudo mkdir -p /root/.cloudflared\nsudo cp config.yml cert.pem <tunnel-id>.json /root/.cloudflared/" },
      { p: "The ingress in **`/root/.cloudflared/config.yml`** must map the hostname to the dashboard port:" },
      { code: "tunnel: <tunnel-id>\ncredentials-file: /root/.cloudflared/<tunnel-id>.json\n\ningress:\n  - hostname: ecrpfm.com\n    service: http://localhost:3000\n  - hostname: www.ecrpfm.com\n    service: http://localhost:3000\n  - service: http_status:404" },
      { p: "Run it (prod supervises `cloudflared` with **PM2**; systemd works just as well):" },
      { code: "# PM2 (matches current prod)\npm2 start \"cloudflared tunnel run <tunnel-id>\" --name cloudflared\npm2 save\n\n# — or — install it as a systemd service instead\nsudo cloudflared service install\nsudo systemctl enable --now cloudflared" },
      { note: { tone: "warn", text: "**Option B — new tunnel:** run `cloudflared tunnel login`, `cloudflared tunnel create meridian`, then `cloudflared tunnel route dns meridian ecrpfm.com` (and `www`). In the Cloudflare DNS panel the record becomes a CNAME to `<tunnel-id>.cfargotunnel.com`. Only one tunnel should own the hostname at a time — stop the old one before cutting over to avoid split routing." } },
    ],
  },
  {
    id: "discord",
    title: "8 · Discord app settings that must match",
    blocks: [
      { note: { tone: "info", text: "**In plain terms:** the bot and the staff login are both run by one Discord “application.” As long as you keep control of that Discord developer account, you keep the bot." } },
      { p: "The bot and dashboard log in through one Discord application. If you keep the same app + token, no Discord changes are needed beyond confirming these. If you rotate the token/secret, update `.env` accordingly." },
      { p: "**OAuth2 → Redirects** must contain both callback URLs (built from `BASE_URL`):" },
      { code: "https://ecrpfm.com/api/auth/callback/discord\nhttps://ecrpfm.com/api/auth/verify/callback" },
      { table: { head: ["Setting", "Value"], rows: [
        ["Bot intents", "Server Members + Message Content (Bot tab → Privileged Gateway Intents)"],
        ["Login scopes", "`identify` (main) and `identify guilds` (verify flow) — set in code, no action needed"],
        ["Slash commands", "Registered **per-guild** to `GUILD_ID` on every bot boot — they appear instantly, no global wait"],
        ["Bot in server", "The bot user must still be a member of the `GUILD_ID` server with its roles"],
      ] } },
      { note: { tone: "info", text: "Dashboard access is role-derived at login: the L3 roles `fm_leadership`, `game_affairs`, `founder`, `executive_admin` map to clearance 3; L2/L1 come from the configured team-lead/guide roles. Individual overrides live in the `dashboard_access` table (managed from **Operations → DB Site Access**)." } },
    ],
  },
  {
    id: "verify",
    title: "9 · Start & verify the cutover",
    blocks: [
      { p: "With services up and the tunnel pointed at the new box:" },
      { code: "# dashboard responds locally (307 = normal auth redirect, NOT an error)\ncurl -s -o /dev/null -w '%{http_code}\\n' http://localhost:3000/fm/dashboard\n\n# service health + recent logs\nsystemctl is-active meridian-bot meridian-dashboard\njournalctl -u meridian-bot -n 30 --no-pager      # look for \"Ready as ...\" + \"Commands registered\"\njournalctl -u meridian-dashboard -n 30 --no-pager" },
      { ul: [
        "Bot log shows `Ready as Meridian Database#…` and `Commands registered`.",
        "Visit `https://ecrpfm.com` through the tunnel and complete a Discord login end-to-end.",
        "Run `/matrix teams` in Discord and open a couple of dashboard tabs to confirm live DB reads.",
        "Confirm the bot is online in the server member list.",
      ] },
      { note: { tone: "warn", text: "Cut over during a quiet window. Because both old and new boxes point at their own copy of the DB, any writes on the old server after you took the snapshot are lost — stop the old services (`systemctl stop meridian-bot meridian-dashboard`) before flipping the tunnel so nothing is written to the stale copy." } },
    ],
  },
  {
    id: "ops",
    title: "10 · Day-to-day: how to deploy changes",
    blocks: [
      { p: "Keep this handy — the two apps deploy differently:" },
      { table: { head: ["Change to…", "Command"], rows: [
        ["**Bot** (`bot/`)", "`sudo systemctl restart meridian-bot` — re-registers slash commands on boot"],
        ["**Dashboard** (`dashboard/`)", "`cd /opt/meridian/dashboard && npm run build && sudo systemctl restart meridian-dashboard`"],
        ["**Data only** (SQLite rows)", "No restart — both live services see committed writes immediately"],
      ] } },
      { note: { tone: "warn", text: "`start.sh` will **not** build for you — editing dashboard source without `npm run build` serves the OLD `.next`. Always build before restarting the dashboard." } },
      { p: "**Before any data edit**, back up first:" },
      { code: "cd /opt/meridian/data\nsqlite3 meridian.db \".backup 'meridian.db.bak-<desc>-$(date +%F)'\"" },
      { note: { tone: "info", text: "SQLite dates are inconsistent across tables (`scene_logs.date` is `DD/MON/YYYY`, `tasks.created_at` is ISO 8601). When inserting rows, match the column's existing format or you'll break `ORDER BY` string sorts. Set up an offsite copy of `meridian.db` on a schedule — it's the only stateful thing here." } },
    ],
  },
  {
    id: "reference",
    title: "11 · Quick reference",
    blocks: [
      { table: { head: ["Thing", "Value"], rows: [
        ["Repo root", "`/opt/meridian`"],
        ["Database", "`/opt/meridian/data/meridian.db` (WAL)"],
        ["Env file", "`/opt/meridian/.env` (chmod 600)"],
        ["Dashboard port", "`3000` (internal; public via tunnel)"],
        ["Node version", "`v22.x`"],
        ["Services", "`meridian-bot.service`, `meridian-dashboard.service`"],
        ["Public URL", "`https://ecrpfm.com`"],
        ["Proxy", "Cloudflare Tunnel → `localhost:3000`"],
        ["Default GUILD_ID", "`1457188814916423855`"],
        ["Game Affairs role ID", "`1457189093594239147`"],
      ] } },
      { note: { tone: "info", text: "This page is visible only to L3 — FM Leadership and Game Affairs Management. Hand it, the `.env`, the Discord app ownership, and the Cloudflare account access to whoever takes over. Losing the Cloudflare tunnel credentials or the Discord app ownership is the hardest part to recover, so transfer those deliberately." } },
    ],
  },
];

// ── "Run it yourself" — set Meridian up from scratch on your own computer ──
// Written for the next head of FM (or a helper they trust), assuming no server
// access and no technical background. Every command is copy-paste.
export const SELF_HOST_GUIDE = [
  {
    id: "sh-what",
    title: "What you're doing, and what you need",
    blocks: [
      { p: "Meridian is three things: the **website** (this dashboard), the **Discord bot**, and one **database file** that holds every record. The website and the bot are just two windows onto that one file. This guide gets all three running on a computer you control — a laptop is fine to start with." },
      { p: "**You will need:**" },
      { ul: [
        "A Windows, Mac or Linux computer and about an hour. Nothing gets installed that you can't remove afterwards.",
        "The **code** and the **database** — both are one click away on the **Export the data** tab of this page (“Download the code” and “Download the database”). Do that first, while you still have access here.",
        "A Discord account, and a Discord **server** you own or admin (the bot needs somewhere to live). Your existing server is fine.",
        "Your own **Discord user ID** — in Discord, *Settings → Advanced → Developer Mode* on, then right-click your name → *Copy User ID*. It's a long number.",
      ] },
      { note: { tone: "info", text: "**Words you'll see:** the **terminal** is the text window where you type commands (Windows: search for *PowerShell*; Mac: *Terminal*). **Node.js** is the program that runs the code. A **folder** is where all of this lives — the guide assumes `meridian` inside your home folder, but anywhere works." } },
      { note: { tone: "warn", text: "Not into this at all? That's fine — hand this page to anyone who has ever run a Node.js project and they'll be done in an hour. Print it with the button above. The **Export the data** tab needs no technical steps at all if you only want the records in Google Sheets." } },
    ],
  },
  {
    id: "sh-install",
    title: "1 · Install Node.js",
    blocks: [
      { p: "Go to **https://nodejs.org** and download the **LTS** version (22.x). Run the installer with the defaults. On Windows, if it offers to install “additional tools”, say yes." },
      { p: "Open a terminal and check it worked — both lines should print a version number:" },
      { code: "node -v\nnpm -v" },
    ],
  },
  {
    id: "sh-files",
    title: "2 · Put the code and the database in place",
    blocks: [
      { ul: [
        "Unzip the **code** download. It contains a folder called `meridian`. Move it to your home folder (Windows: `C:\\Users\\<you>\\meridian`; Mac/Linux: `~/meridian`).",
        "Inside it, create a folder called **`data`** and put the **database** download in it, renamed to exactly **`meridian.db`**. So you end up with `meridian/data/meridian.db`.",
      ] },
      { note: { tone: "info", text: "The database file **is** Meridian's memory: every faction, member, review, scene, property, NPC. Keep a spare copy of it somewhere safe (Google Drive, a USB stick) before you do anything else. If a step below goes wrong, this file is the only thing that can't be re-downloaded from the internet." } },
      { note: { tone: "warn", text: "The **map background images** (about 700 MB) are too big to be in the code download. Everything else works without them; the map page just shows no background. Ask the previous head for a copy of the `dashboard/public/map-tiles` folder if you want the map." } },
    ],
  },
  {
    id: "sh-discord",
    title: "3 · Create your Discord bot",
    blocks: [
      { p: "The bot and the website login are both one Discord “application”. Make your own — it takes five minutes and you'll own it outright." },
      { ul: [
        "Go to **https://discord.com/developers/applications** → **New Application** → name it (e.g. *Meridian*).",
        "**General Information**: copy the **Application ID** — you'll need it in the next step.",
        "**OAuth2**: click **Reset Secret**, copy the **Client Secret**. Under **Redirects** add these two lines, then Save:",
      ] },
      { code: "http://localhost:3000/api/auth/callback/discord\nhttp://localhost:3000/api/auth/verify/callback" },
      { ul: [
        "**Bot**: click **Reset Token**, copy the **Token** (shown once — save it now). Further down, switch on **Server Members Intent** and **Message Content Intent**, then Save.",
        "**Invite the bot to your server**: OAuth2 → *URL Generator* → tick `bot` and `applications.commands` → under Bot Permissions tick **Administrator** → open the generated link in your browser and pick your server.",
        "Get your **server's ID**: in Discord, right-click the server icon → *Copy Server ID* (needs Developer Mode, see above).",
      ] },
      { note: { tone: "danger", text: "The **token** and **client secret** are passwords. Never paste them in Discord or anywhere public. If one leaks, press *Reset* in the developer portal and update the settings file below." } },
    ],
  },
  {
    id: "sh-env",
    title: "4 · Fill in the settings file",
    blocks: [
      { p: "In the `meridian` folder there is a file called **`.env.example`**. Make a copy of it named exactly **`.env`** (note the dot at the start — on Windows, name it `.env.` and Explorer will drop the trailing dot). Open it in Notepad / TextEdit and fill in the values. Anything not listed here can stay blank." },
      { table: { head: ["Setting", "What to put"], rows: [
        ["`DISCORD_CLIENT_ID`", "The **Application ID** from step 3"],
        ["`DISCORD_CLIENT_SECRET`", "The **Client Secret** from step 3"],
        ["`DISCORD_BOT_TOKEN`", "The bot **Token** from step 3"],
        ["`GUILD_ID`", "Your **server ID** from step 3"],
        ["`DATABASE_PATH`", "The full path to the database file, e.g. `C:\\Users\\you\\meridian\\data\\meridian.db` or `/Users/you/meridian/data/meridian.db`"],
        ["`BASE_URL`", "`http://localhost:3000` (exactly — it must match the redirects in step 3)"],
        ["`NODE_ENV`", "`production`"],
        ["`SESSION_SECRET`", "Any long random text — mash the keyboard for 40+ characters"],
        ["`RISK_DISCORD_ID`", "Remove the `#` at the start of this line and put **your own Discord user ID**. This makes you the owner: full access on your very first login, before any roles are set up"],
      ] } },
      { note: { tone: "info", text: "`OPENAI_API_KEY`, `IMGBB_API_KEY`, `NOTIFY_SECRET` and `AGENDA_SECRET` are optional extras (AI summaries, image uploads, form-intake and agenda links). Leave them blank; those features simply stay off." } },
    ],
  },
  {
    id: "sh-build",
    title: "5 · Install and build (one-time)",
    blocks: [
      { p: "In a terminal, go into the `meridian` folder and run these, one line at a time. The `npm install` steps download the building blocks the code needs (a few minutes each); `npm run build` packages the website (a few minutes, the computer will get busy)." },
      { code: "cd ~/meridian          # Windows: cd $HOME\\meridian\nnpm install\ncd bot\nnpm install\ncd ../dashboard\nnpm install\nnpm run build" },
      { note: { tone: "warn", text: "If `npm install` fails mentioning **python**, **gyp** or **build tools**, the database driver couldn't find a compiler. Windows: run the Node.js installer again and tick *“Automatically install the necessary tools”*. Mac: run `xcode-select --install`. Linux: `sudo apt install build-essential python3`. Then run `npm install` again." } },
    ],
  },
  {
    id: "sh-run",
    title: "6 · Start it up",
    blocks: [
      { p: "You need **two** terminal windows — one for the website, one for the bot. Each keeps running while its window is open." },
      { p: "**Window 1 — the website:**" },
      { code: "cd ~/meridian/dashboard\nnpm start" },
      { p: "**Window 2 — the bot:**" },
      { code: "cd ~/meridian/bot\nnode index.js" },
      { p: "Now open **http://localhost:3000** in your browser and log in with Discord. Because your ID is `RISK_DISCORD_ID`, you'll land on the dashboard with full access. In Discord, the bot should show as online and `/` commands should appear." },
      { note: { tone: "info", text: "**Something not right?** The terminal window tells you why. *“not in server”* on login → you're not a member of the `GUILD_ID` server, or the bot isn't in it. *“unauthorized”* → `RISK_DISCORD_ID` isn't your ID, or still has the `#` in front. Bot fails instantly → the token is wrong or an intent in step 3 is off. Changed `.env`? Stop both windows (Ctrl+C) and start them again." } },
    ],
  },
  {
    id: "sh-after",
    title: "7 · Make it yours",
    blocks: [
      { p: "Everything works, but the data still points at the old Discord server: role IDs, channel IDs and ping routes. Fix that from inside the dashboard — no code involved:" },
      { ul: [
        "**Admin → Discord & Access**: map each role (leadership, team lead, guide, event team…) to the matching role in *your* server, and point each channel setting at your channels. From then on, people log in and get the right access from their roles, exactly as before.",
        "**Admin → Discord & Access → site access**: grant anyone who should get in before roles are sorted.",
        "**Admin → Staff & Teams**: the staff roster and team channels.",
        "Recurring reminders, ping routes and announcement targets are all under **Admin** too — go through each once.",
      ] },
      { note: { tone: "info", text: "Get people in the habit of copying `data/meridian.db` somewhere safe regularly — it's the only file that matters. The Export tab of this page keeps working on your copy, so you can always pull a fresh database or CSV bundle from there." } },
    ],
  },
  {
    id: "sh-public",
    title: "8 · Optional: put it on the internet",
    blocks: [
      { p: "Running on a laptop means it's only up while the laptop is. To have it online 24/7 at a web address, someone needs a small always-on Linux machine (any ~£5/month VPS with 2 GB memory) and a domain. That's a step up in technical terms — this is where you hand over to a helper, together with the **Technical runbook** tab, which covers the server setup, the services that keep it running, and the Cloudflare tunnel that provides the address and the padlock." },
      { ul: [
        "On the server, `BASE_URL` becomes your real address (e.g. `https://yourdomain.com`) and the two Discord redirects in step 3 change to match.",
        "The service files in the `deploy/` folder keep the website and bot running and restart them after reboots.",
        "Nightly backups: `deploy/meridian-backup.timer` + `scripts/backup.sh` do that automatically.",
      ] },
      { note: { tone: "info", text: "**Getting future code updates.** The code lives at **github.com/riskecrp/meridian** (private). Ask the previous head to add you as a collaborator; then `git pull` on your copy brings in changes. Without that, the code zip you downloaded is a complete, frozen copy — it keeps working indefinitely." } },
    ],
  },
];
